# Generated by Django 2.0 on 2023-07-05 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('puntos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ColorDeportePuntos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='core.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', help_text='Codigo Corto', max_length=5)),
                ('nombre', models.CharField(help_text='Descripcion', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=100)),
                ('resultado_local', models.PositiveIntegerField(blank=True, null=True)),
                ('resultado_visitante', models.PositiveIntegerField(blank=True, null=True)),
                ('puntos_ganador', models.IntegerField(default=3, help_text='Define los puntos otorgados al ganador')),
                ('puntos_empate', models.IntegerField(default=1, help_text='Define los puntos otorgados el empate')),
                ('finalizado', models.BooleanField(default=False)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Deporte')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puntos', models.IntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colores', to='core.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_jugador', to='core.Color')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='core.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='core.Torneo'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='equipo_ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuentros_e_ganados', to='core.Equipo'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='equipo_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuentros_locales', to='core.Equipo'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='equipo_visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuentros_visitantes', to='core.Equipo'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='judador_visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuentros_visitantes', to='core.Jugador'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='jugador_ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuentros_j_ganados', to='core.Jugador'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='jugador_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuentros_locales', to='core.Jugador'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Torneo'),
        ),
        migrations.AddField(
            model_name='deporte',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Torneo'),
        ),
        migrations.AddField(
            model_name='colordeportepuntos',
            name='deporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Deporte'),
        ),
        migrations.AddField(
            model_name='colordeportepuntos',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Torneo'),
        ),
        migrations.AddField(
            model_name='color',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Torneo'),
        ),
    ]
